insert into address (street, city, zipcode) values ('Mccormick', 'Birātnagar', null);
insert into address (street, city, zipcode) values ('Portage', 'Waepana', null);
insert into address (street, city, zipcode) values ('Dexter', 'Dawung', null);
insert into address (street, city, zipcode) values ('Eagan', 'Strellc i Epërm', null);
insert into address (street, city, zipcode) values ('Monica', 'Vitebsk', null);
insert into address (street, city, zipcode) values ('Fulton', 'Matos da Ranha', '3105-378');
insert into address (street, city, zipcode) values ('Sundown', 'Proptisht', null);
insert into address (street, city, zipcode) values ('Dennis', 'Xiang Ngeun', null);
insert into address (street, city, zipcode) values ('Anthes', 'Chong’ansi', null);
insert into address (street, city, zipcode) values ('Kipling', 'Fujioka', '999-7638');
insert into address (street, city, zipcode) values ('Elmside', 'Nagornyy', '142817');
insert into address (street, city, zipcode) values ('Grover', 'Irará', '44255-000');
insert into address (street, city, zipcode) values ('Larry', 'Gouyan', null);
insert into address (street, city, zipcode) values ('Old Gate', 'Diffa', null);
insert into address (street, city, zipcode) values ('Myrtle', 'Tingloy', '4203');
insert into address (street, city, zipcode) values ('Melrose', 'Abashiri', '336-0926');
insert into address (street, city, zipcode) values ('Welch', 'Nelspruit', '1360');
insert into address (street, city, zipcode) values ('Redwing', 'Koktal', null);
insert into address (street, city, zipcode) values ('Blaine', 'Bento Gonçalves', '95700-000');
insert into address (street, city, zipcode) values ('Union', 'Liuhe', null);
insert into address (street, city, zipcode) values ('Del Sol', 'Ýdra', null);
insert into address (street, city, zipcode) values ('Division', 'Qorashina', null);
insert into address (street, city, zipcode) values ('Warner', 'Ekenäs', '35530');
insert into address (street, city, zipcode) values ('Golf', 'Guadalupe', '3510');
insert into address (street, city, zipcode) values ('Novick', 'Triánta', null);
insert into address (street, city, zipcode) values ('Mandrake', 'Pavlohrad', null);
insert into address (street, city, zipcode) values ('Carioca', 'Guoyuan', null);
insert into address (street, city, zipcode) values ('Crowley', 'Odiongan', '5505');
insert into address (street, city, zipcode) values ('Kipling', 'Saint-Denis', '97701 CEDEX 9');
insert into address (street, city, zipcode) values ('Carberry', 'Heemskerk', '1964');
insert into address (street, city, zipcode) values ('Hagan', 'Haixing', null);
insert into address (street, city, zipcode) values ('Nobel', 'Stamáta', null);
insert into address (street, city, zipcode) values ('Claremont', 'Anju', null);
insert into address (street, city, zipcode) values ('Eggendart', 'Phú Khương', null);
insert into address (street, city, zipcode) values ('Becker', 'Karagay', '617210');
insert into address (street, city, zipcode) values ('Westport', 'Sarukhan', null);
insert into address (street, city, zipcode) values ('Fordem', 'Sychëvo', '673550');
insert into address (street, city, zipcode) values ('Northview', 'Ilandža', null);
insert into address (street, city, zipcode) values ('Elmside', 'Kongsvinger', '2205');
insert into address (street, city, zipcode) values ('Hauk', 'Tajan', null);
insert into address (street, city, zipcode) values ('Bonner', 'Mesopotamía', null);
insert into address (street, city, zipcode) values ('Tennessee', 'Al ‘Azīzīyah', null);
insert into address (street, city, zipcode) values ('Caliangt', 'Bendilmuning', null);
insert into address (street, city, zipcode) values ('Cordelia', 'Haputale', '90160');
insert into address (street, city, zipcode) values ('Westridge', 'Dongdu', null);
insert into address (street, city, zipcode) values ('Bunker Hill', 'Busuanga', '5317');
insert into address (street, city, zipcode) values ('2nd', 'Ritaebang', null);
insert into address (street, city, zipcode) values ('Washington', 'Lazo', '692980');
insert into address (street, city, zipcode) values ('Derek', 'Luzhany', null);
insert into address (street, city, zipcode) values ('Shelley', 'Nasielsk', '05-191');
insert into address (street, city, zipcode) values ('Crowley', 'Smyga', null);
insert into address (street, city, zipcode) values ('Anzinger', 'Onsala', '439 37');
insert into address (street, city, zipcode) values ('Stang', 'Guzhan', null);
insert into address (street, city, zipcode) values ('Lunder', 'Sumbergedong', null);
insert into address (street, city, zipcode) values ('Sunfield', 'Stare Kurowo', '66-540');
insert into address (street, city, zipcode) values ('Ramsey', 'Jonava', '55014');
insert into address (street, city, zipcode) values ('International', 'Floresta', '56400-000');
insert into address (street, city, zipcode) values ('Tomscot', 'Cái Nhum', null);
insert into address (street, city, zipcode) values ('Mcbride', 'Wakefield', null);
insert into address (street, city, zipcode) values ('Anthes', 'Lincoln', '6070');
insert into address (street, city, zipcode) values ('Harbort', 'Botou', null);
insert into address (street, city, zipcode) values ('Sycamore', 'Rîbniţa', 'MD-5519');
insert into address (street, city, zipcode) values ('Glacier Hill', 'Shadili', null);
insert into address (street, city, zipcode) values ('Monterey', 'Moorreesburg', '7312');
insert into address (street, city, zipcode) values ('Maple', 'Zaraysk', '140614');
insert into address (street, city, zipcode) values ('Parkside', 'Baranowo', '06-320');
insert into address (street, city, zipcode) values ('Laurel', 'Zhangshui', null);
insert into address (street, city, zipcode) values ('Cody', 'Luts’k', null);
insert into address (street, city, zipcode) values ('Corben', 'Ōtsuki', '402-0056');
insert into address (street, city, zipcode) values ('Hagan', 'Nasielsk', '05-191');
insert into address (street, city, zipcode) values ('Springview', 'Inderka', '442585');
insert into address (street, city, zipcode) values ('Meadow Valley', 'Escola', '4600-730');
insert into address (street, city, zipcode) values ('Farwell', 'Baitashan', null);
insert into address (street, city, zipcode) values ('Towne', 'Tabia', null);
insert into address (street, city, zipcode) values ('Merrick', 'Karlskoga', '691 21');
insert into address (street, city, zipcode) values ('Hooker', 'Chenxikou', null);
insert into address (street, city, zipcode) values ('Vidon', 'Tatarka', '356235');
insert into address (street, city, zipcode) values ('Scoville', 'Telhado', '4850-162');
insert into address (street, city, zipcode) values ('Cascade', 'Winschoten', '9674');
insert into address (street, city, zipcode) values ('Pond', 'Gastoúni', null);
insert into address (street, city, zipcode) values ('Grayhawk', 'Causip', '4430');
insert into address (street, city, zipcode) values ('Oriole', 'Detchino', '249080');
insert into address (street, city, zipcode) values ('Bluejay', 'Talok', null);
insert into address (street, city, zipcode) values ('Farmco', 'Orzu', null);
insert into address (street, city, zipcode) values ('Susan', 'North Saanich', 'K6A');
insert into address (street, city, zipcode) values ('Bartillon', 'Joaquín V. González', '4448');
insert into address (street, city, zipcode) values ('7th', 'Novki', '601340');
insert into address (street, city, zipcode) values ('Cordelia', 'Thị Trấn Bắc Hà', null);
insert into address (street, city, zipcode) values ('Riverside', 'Tolosa', '6503');
insert into address (street, city, zipcode) values ('Anniversary', 'Bayt Sāḩūr', null);
insert into address (street, city, zipcode) values ('Mosinee', 'Azara', '3351');
insert into address (street, city, zipcode) values ('American', 'Wenchi', null);
insert into address (street, city, zipcode) values ('Jenifer', 'Zhuangxing', null);
insert into address (street, city, zipcode) values ('Kennedy', 'Malanville', null);
insert into address (street, city, zipcode) values ('Melrose', 'Al ‘Āliyah', null);
insert into address (street, city, zipcode) values ('Corry', 'Atok', '2612');
insert into address (street, city, zipcode) values ('Heffernan', 'Fufang', null);
insert into address (street, city, zipcode) values ('Calypso', 'Umeå', '903 33');
insert into address (street, city, zipcode) values ('Springview', 'Leigongmiao', null);
insert into address (street, city, zipcode) values ('New Castle', 'Darungan Lor', null);
